from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional


ROOT = Path("JARVIS_CORE")
LOG_DIR = ROOT / "runtime_logs"

EVENTS_FILE = LOG_DIR / "runtime_events.jsonl"
TIMELINE_FILE = LOG_DIR / "runtime_timeline.jsonl"
WAKE_FILE = LOG_DIR / "runtime_wake_events.jsonl"
STATE_FILE = LOG_DIR / "runtime_wake_state.json"


class RuntimeWakeSupervisor:
    """
    Safe bounded wake supervisor.

    This supervisor does NOT execute shell commands.
    It does NOT apply patches.
    It only observes runtime telemetry and emits wake/silence events.
    """

    def __init__(self, silence_seconds: int = 60, heartbeat_stale_seconds: int = 90):
        self.silence_seconds = silence_seconds
        self.heartbeat_stale_seconds = heartbeat_stale_seconds
        LOG_DIR.mkdir(parents=True, exist_ok=True)

    def utc_now(self) -> datetime:
        return datetime.now(timezone.utc)

    def iso_now(self) -> str:
        return self.utc_now().isoformat().replace("+00:00", "Z")

    def read_last_jsonl(self, path: Path) -> Optional[Dict[str, Any]]:
        if not path.exists():
            return None

        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except Exception:
            return None

        for line in reversed(lines):
            line = line.strip()
            if not line:
                continue
            try:
                return json.loads(line)
            except json.JSONDecodeError:
                continue

        return None

    def parse_timestamp(self, value: Optional[str]) -> Optional[datetime]:
        if not value:
            return None

        try:
            value = value.replace("Z", "+00:00")
            return datetime.fromisoformat(value)
        except Exception:
            return None

    def seconds_since(self, timestamp: Optional[str]) -> Optional[float]:
        dt = self.parse_timestamp(timestamp)
        if dt is None:
            return None
        return (self.utc_now() - dt).total_seconds()

    def append_jsonl(self, path: Path, payload: Dict[str, Any]) -> None:
        with path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(payload, ensure_ascii=False) + "\n")

    def save_state(self, state: Dict[str, Any]) -> None:
        STATE_FILE.write_text(json.dumps(state, ensure_ascii=False, indent=2), encoding="utf-8")

    def inspect(self) -> Dict[str, Any]:
        last_event = self.read_last_jsonl(EVENTS_FILE)
        last_timeline = self.read_last_jsonl(TIMELINE_FILE)

        last_event_age = self.seconds_since(last_event.get("timestamp")) if last_event else None
        last_timeline_age = self.seconds_since(last_timeline.get("timestamp")) if last_timeline else None

        silence_detected = (
            last_timeline_age is None or last_timeline_age >= self.silence_seconds
        )

        heartbeat_stale = (
            last_event_age is None or last_event_age >= self.heartbeat_stale_seconds
        )

        wake_needed = bool(silence_detected or heartbeat_stale)

        state = {
            "timestamp": self.iso_now(),
            "supervisor": "runtime_wake_supervisor",
            "mode": "bounded_safe_observation",
            "wake_needed": wake_needed,
            "silence_detected": silence_detected,
            "heartbeat_stale": heartbeat_stale,
            "last_event_age_seconds": last_event_age,
            "last_timeline_age_seconds": last_timeline_age,
            "thresholds": {
                "silence_seconds": self.silence_seconds,
                "heartbeat_stale_seconds": self.heartbeat_stale_seconds,
            },
            "last_event": last_event,
            "last_timeline": last_timeline,
            "safety": {
                "shell_execution": False,
                "patch_apply": False,
                "auto_repair": False,
                "bounded": True,
            },
        }

        return state

    def tick(self) -> Dict[str, Any]:
        state = self.inspect()

        event_type = "wake_signal" if state["wake_needed"] else "observe_and_continue"

        wake_event = {
            "timestamp": self.iso_now(),
            "event_type": event_type,
            "source": "runtime_wake_supervisor",
            "message": (
                "Wake signal generated by safe bounded supervisor"
                if state["wake_needed"]
                else "Runtime observation healthy; continue monitoring"
            ),
            "payload": {
                "wake_needed": state["wake_needed"],
                "silence_detected": state["silence_detected"],
                "heartbeat_stale": state["heartbeat_stale"],
                "last_event_age_seconds": state["last_event_age_seconds"],
                "last_timeline_age_seconds": state["last_timeline_age_seconds"],
            },
            "safety": state["safety"],
        }

        self.append_jsonl(WAKE_FILE, wake_event)
        self.save_state(state)

        return {
            "processed": True,
            "event_type": event_type,
            "wake_needed": state["wake_needed"],
            "silence_detected": state["silence_detected"],
            "heartbeat_stale": state["heartbeat_stale"],
            "state_file": str(STATE_FILE),
            "wake_file": str(WAKE_FILE),
        }


def main() -> None:
    supervisor = RuntimeWakeSupervisor()
    result = supervisor.tick()
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
